# -*- coding: utf-8 -*-
"""Coding practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR7scPjTTBmFsYBgufXlAbwfU5-_1NVs
"""

#problem 1
w=int(input("w "))
if w>2 and w%2==0:
  print("yes")
else:
  print("no")

#sample code
print("hello world")

#hackerrank runup problem
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    arr1 = set(arr)
    arr2 = sorted(arr1)
    print(arr2[-2])